version: '3'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - backend
      - frontend
    container_name: backend

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - frontend
    restart: unless-stopped
    container_name: frontend

networks:
  backend:
  frontend:
