version: '3.8'

services:
  backend:
    build: ./backend
    restart: unless-stopped
    ports:
      - "5000:5000"
    networks:
      - backend
      - frontend

  frontend:
    depends_on:
      - backend
    build:
      context: ./frontend
    ports:
      - "80:80"
    networks:
      - frontend  

networks:
  backend:
  frontend: